# Generated by Django 4.1 on 2023-06-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('elevacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'imagen',
            },
        ),
        migrations.CreateModel(
            name='imagenApt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=55)),
                ('elevacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='home')),
            ],
            options={
                'verbose_name': 'ImagenApt',
            },
        ),
        migrations.CreateModel(
            name='passSatellite',
            fields=[
                ('noradId', models.IntegerField(primary_key=True, serialize=False)),
                ('satname', models.CharField(max_length=50)),
                ('transactionscount', models.IntegerField()),
                ('startAz', models.CharField(max_length=25)),
                ('endAz', models.CharField(max_length=25)),
                ('startUTC', models.CharField(max_length=75)),
                ('endUTC', models.CharField(max_length=25)),
                ('maxEl', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'passSatellite',
            },
        ),
        migrations.CreateModel(
            name='sat',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('noradId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Sat',
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('noradId', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Satellite',
            },
        ),
    ]
