# Generated by Django 4.1 on 2023-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaaWebApp', '0002_alter_imagenapt_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenapt',
            name='imagen',
            field=models.ImageField(upload_to='noaaWebApp/static/images'),
        ),
    ]
