# Generated by Django 4.1.1 on 2022-09-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaaWebApp', '0002_satellite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idsatellite',
            name='id',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='id',
        ),
        migrations.AddField(
            model_name='idsatellite',
            name='noradId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='satellite',
            name='noradId',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
