# Generated by Django 4.1.1 on 2022-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaaWebApp', '0003_remove_idsatellite_id_remove_satellite_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idsatellite',
            name='noradId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='noradId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
