# Generated by Django 4.1 on 2023-06-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaaWebApp', '0003_alter_imagenapt_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenapt',
            name='imagen',
            field=models.ImageField(upload_to='noaaWebApp'),
        ),
    ]
