# Generated by Django 4.1.1 on 2022-09-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noaaWebApp', '0004_alter_idsatellite_noradid_alter_satellite_noradid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='idSatellite',
        ),
    ]
