# Generated by Django 4.1 on 2023-06-09 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noaaWebApp', '0004_alter_imagenapt_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenapt',
            name='audio',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media/noaaWebApp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagenapt',
            name='imagen',
            field=models.ImageField(upload_to='media/noaaWebApp'),
        ),
    ]
