# Generated by Django 4.1 on 2023-06-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noaaWebApp', '0005_imagenapt_audio_alter_imagenapt_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenapt',
            name='audio',
            field=models.FileField(null=True, upload_to='media/noaaWebApp'),
        ),
    ]
